/**
 * Builds an idempotent SQL seed script from /seed/*.json (BLUEPRINT.md golden rule 2).
 * Every statement is INSERT OR IGNORE / guarded, so re-running never overwrites existing rows.
 */
import { z } from "zod";
import { ADMIN_ROLES } from "./schema";
import { SETTING_KEYS, settingsSchemas, type SettingKey } from "@/lib/schemas/settings";

export const SEED_ACTOR = "seed";

export const seedAdminUserSchema = z.object({
  email: z.email().transform((e) => e.toLowerCase()),
  name: z.string().min(1),
  role: z.enum(ADMIN_ROLES),
  smsPhone: z.string().nullable(),
});

export const seedTemplateSchema = z.object({
  key: z.string().regex(/^[a-z0-9_]+$/),
  channel: z.enum(["email", "sms", "push"]),
  subject: z.string().nullable(),
  body: z.string().min(1),
  enabled: z.boolean(),
});

export type SeedInput = {
  settings: Record<string, unknown>;
  adminUsers: unknown[];
  templates?: unknown[];
};

export function sqlString(value: string | null): string {
  return value === null ? "NULL" : `'${value.replaceAll("'", "''")}'`;
}

export function buildSeedSql(input: SeedInput, now: string = new Date().toISOString()): string {
  const lines: string[] = [
    "-- Generated by scripts/seed.ts. Safe to re-run: never overwrites rows.",
  ];

  for (const key of SETTING_KEYS) {
    if (!(key in input.settings)) throw new Error(`seed/settings.json is missing "${key}"`);
    const value = settingsSchemas[key as SettingKey].parse(input.settings[key]);
    const json = sqlString(JSON.stringify(value));
    const k = sqlString(key);
    // History first, only when the setting doesn't exist yet, so every pricing version has an id.
    lines.push(
      `INSERT OR IGNORE INTO settings_history (id, key, old_value, new_value, changed_by, changed_at) ` +
        `SELECT ${sqlString(`seed-${key}`)}, ${k}, NULL, ${json}, '${SEED_ACTOR}', ${sqlString(now)} ` +
        `WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key = ${k});`,
      `INSERT OR IGNORE INTO settings (key, value, updated_at, updated_by) VALUES (${k}, ${json}, ${sqlString(now)}, '${SEED_ACTOR}');`,
    );
  }

  for (const raw of input.adminUsers) {
    const u = seedAdminUserSchema.parse(raw);
    lines.push(
      `INSERT OR IGNORE INTO admin_users (email, name, role, active, sms_phone) VALUES (` +
        `${sqlString(u.email)}, ${sqlString(u.name)}, ${sqlString(u.role)}, 1, ${sqlString(u.smsPhone)});`,
    );
  }

  for (const raw of input.templates ?? []) {
    const t = seedTemplateSchema.parse(raw);
    lines.push(
      `INSERT OR IGNORE INTO message_templates (key, channel, subject, body, enabled, updated_at) VALUES (` +
        `${sqlString(t.key)}, ${sqlString(t.channel)}, ${sqlString(t.subject)}, ${sqlString(t.body)}, ` +
        `${t.enabled ? 1 : 0}, ${sqlString(now)});`,
    );
  }

  return lines.join("\n") + "\n";
}
