/**
 * Builds an idempotent SQL seed script from /seed/*.json (BLUEPRINT.md golden rule 2).
 * Every statement is INSERT OR IGNORE / guarded, so re-running never overwrites existing rows.
 */
import { z } from "@/lib/zod";
import { ADMIN_ROLES } from "./schema";
import { faqSchema, policySchema, serviceSchema } from "@/lib/schemas/content";
import { SETTING_KEYS, settingsSchemas, type SettingKey } from "@/lib/schemas/settings";

export const SEED_ACTOR = "seed";

export const seedAdminUserSchema = z.object({
  email: z.email().transform((e) => e.toLowerCase()),
  name: z.string().min(1),
  role: z.enum(ADMIN_ROLES),
  smsPhone: z.string().nullable(),
});

export const seedTemplateSchema = z.object({
  key: z.string().regex(/^[a-z0-9_]+$/),
  channel: z.enum(["email", "sms", "push"]),
  subject: z.string().nullable(),
  body: z.string().min(1),
  enabled: z.boolean(),
});

export type SeedInput = {
  settings: Record<string, unknown>;
  adminUsers: unknown[];
  templates?: unknown[];
  services?: unknown[];
  faqs?: unknown[];
  policies?: unknown[];
};

const sqlJson = (v: unknown) => sqlString(JSON.stringify(v));
const sqlInt = (v: number | null) => (v === null ? "NULL" : String(Math.trunc(v)));
const sqlBool = (v: boolean) => (v ? "1" : "0");

export function sqlString(value: string | null): string {
  return value === null ? "NULL" : `'${value.replaceAll("'", "''")}'`;
}

/** One SQL statement per array item (statements may span lines inside string literals). */
export function buildSeedStatements(
  input: SeedInput,
  now: string = new Date().toISOString(),
): string[] {
  const lines: string[] = [];

  for (const key of SETTING_KEYS) {
    if (!(key in input.settings)) throw new Error(`seed/settings.json is missing "${key}"`);
    const value = settingsSchemas[key as SettingKey].parse(input.settings[key]);
    const json = sqlString(JSON.stringify(value));
    const k = sqlString(key);
    // History first, only when the setting doesn't exist yet, so every pricing version has an id.
    lines.push(
      `INSERT OR IGNORE INTO settings_history (id, key, old_value, new_value, changed_by, changed_at) ` +
        `SELECT ${sqlString(`seed-${key}`)}, ${k}, NULL, ${json}, '${SEED_ACTOR}', ${sqlString(now)} ` +
        `WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key = ${k});`,
      `INSERT OR IGNORE INTO settings (key, value, updated_at, updated_by) VALUES (${k}, ${json}, ${sqlString(now)}, '${SEED_ACTOR}');`,
    );
  }

  for (const raw of input.adminUsers) {
    const u = seedAdminUserSchema.parse(raw);
    lines.push(
      `INSERT OR IGNORE INTO admin_users (email, name, role, active, sms_phone) VALUES (` +
        `${sqlString(u.email)}, ${sqlString(u.name)}, ${sqlString(u.role)}, 1, ${sqlString(u.smsPhone)});`,
    );
  }

  for (const raw of input.templates ?? []) {
    const t = seedTemplateSchema.parse(raw);
    lines.push(
      `INSERT OR IGNORE INTO message_templates (key, channel, subject, body, enabled, updated_at) VALUES (` +
        `${sqlString(t.key)}, ${sqlString(t.channel)}, ${sqlString(t.subject)}, ${sqlString(t.body)}, ` +
        `${t.enabled ? 1 : 0}, ${sqlString(now)});`,
    );
  }

  for (const raw of input.services ?? []) {
    const v = serviceSchema.parse(raw);
    lines.push(
      `INSERT OR IGNORE INTO services (id, slug, service_key, title, summary, body, checklist, not_included, ` +
        `price_from_cents, bookable, capacity_weight, sort_order, active, seo_title, seo_description, updated_at) VALUES (` +
        [
          sqlString(v.id),
          sqlString(v.slug),
          sqlString(v.serviceKey),
          sqlString(v.title),
          sqlString(v.summary),
          sqlString(v.body),
          sqlJson(v.checklist),
          sqlJson(v.notIncluded),
          sqlInt(v.priceFromCents),
          sqlBool(v.bookable),
          sqlInt(v.capacityWeight),
          sqlInt(v.sortOrder),
          sqlBool(v.active),
          sqlString(v.seoTitle),
          sqlString(v.seoDescription),
          sqlString(now),
        ].join(", ") +
        `);`,
    );
  }

  for (const raw of input.faqs ?? []) {
    const f = faqSchema.parse(raw);
    lines.push(
      `INSERT OR IGNORE INTO faqs (id, question, answer, service_slug, sort_order, active) VALUES (` +
        `${sqlString(f.id)}, ${sqlString(f.question)}, ${sqlString(f.answer)}, ${sqlString(f.serviceSlug)}, ` +
        `${sqlInt(f.sortOrder)}, ${sqlBool(f.active)});`,
    );
  }

  for (const raw of input.policies ?? []) {
    const pol = policySchema.parse(raw);
    lines.push(
      `INSERT OR IGNORE INTO policies (slug, title, body, updated_at) VALUES (` +
        `${sqlString(pol.slug)}, ${sqlString(pol.title)}, ${sqlString(pol.body)}, ${sqlString(now)});`,
    );
  }

  return lines;
}

export function buildSeedSql(input: SeedInput, now: string = new Date().toISOString()): string {
  return (
    "-- Generated by scripts/seed.ts. Safe to re-run: never overwrites rows.\n" +
    buildSeedStatements(input, now).join("\n") +
    "\n"
  );
}
