/**
 * Custom Worker entry: OpenNext's fetch handler + Cron Triggers.
 * scheduled() runs each job by POSTing to the app's own /api/cron/<job> route with CRON_SECRET, so all
 * job code lives (and is tested) inside the Next.js app. Schedule: lib/cron/schedule.ts.
 * .open-next/worker.js only exists after a build, hence the ts-ignore on that import.
 */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- the file may or may not exist yet
// @ts-ignore — generated by `opennextjs-cloudflare build`
import { default as openNext } from "./.open-next/worker.js";

const handler = openNext as ExportedHandler<CloudflareEnv> & {
  fetch: (req: Request, env: CloudflareEnv, ctx: ExecutionContext) => Promise<Response>;
} satisfies ExportedHandler<CloudflareEnv>;
import { CRON_JOBS } from "./lib/cron/schedule";

export default {
  fetch: handler.fetch,

  async scheduled(controller: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    const jobs = CRON_JOBS[controller.cron] ?? [];
    for (const job of jobs) {
      ctx.waitUntil(
        handler
          .fetch(
            new Request(`https://cron.internal/api/cron/${job}`, {
              method: "POST",
              headers: { "x-cron-secret": env.CRON_SECRET ?? "" },
            }),
            env,
            ctx,
          )
          .then(async (res) =>
            console.log(`cron ${controller.cron} ${job}: ${res.status} ${await res.text()}`),
          ),
      );
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;
